# # This file should contain all the record creation needed to seed the database with its default values.
# # The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
# #
# # Examples:
# #
# #   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
# #   Character.create(name: 'Luke', movie: movies.first)

# Category.create(name: "Carribbean")
# Category.create(name: "American")
# Category.create(name: "Cafe")

# Place.create(name: "14 Parish Restaurant & Rhum Bar", api_place_id: "ic1X0dPQQK7VAJOsvxLYUQ", bar: true, image_url: "https://s3-media3.fl.yelpcdn.com/bphoto/2WYqzwalAfJ0tLlK_cqnYg/o.jpg", lat: 41.799815, lon: -87.584843, category_id: 1)
# Place.create(name: "5 Loaves Eatery", api_place_id: "V4UEL-OmlUHa6-hNpu4N6Q", bar: false, image_url: "https://s3-media1.fl.yelpcdn.com/bphoto/AZBMmKqhw3-prt3v6QJmew/o.jpg", lat: 41.7582923, lon: -87.6147692, category_id: 2)
# Place.create(name: "Ain't She Sweet Cafe", api_place_id: "IRnNJNVlSyhQG0lBfzsZaA", bar: false, image_url: "https://s3-media2.fl.yelpcdn.com/bphoto/99TZgCMxiLxeoLlDLJvL7w/o.jpg", lat: 41.8168655, lon: -87.612947, category_id: 3)
# Place.create(name: "AndySunflower Cafe", api_place_id: "Imy7MhrTq0z-GQ5RjN_USg", bar: false, image_url: "https://s3-media2.fl.yelpcdn.com/bphoto/PmFDIyonCVWAcg8dsW6mtA/o.jpg", lat: 41.713268, lon: -87.682102, category_id: 3)

# Place.create(name: "B&B's Ice Cream and Candy", category_id: 3)
# Place.create(name: "BigCity CheeseSteaks", category_id: 2)


# User.create(name: "testname", email: "testemail", password_digest: "testdigest")

# Favorite.create(user_id: 1, place_id: 1)
# Favorite.create(user_id: 1, place_id: 2)
# Favorite.create(user_id: 1, place_id: 4)

Place.create(name: "B'Gabs Vegan Kitchen", category_id: 4)
Place.create(name: "Bani's Beets", category_id: 4)
Place.create(name: "BaseHit BBQ & Catering", category_id: 4)
Place.create(name: "Batter & Berries", category_id: 4)
Place.create(name: "Bear Down Barbecue & Catering Co.", category_id: 4)
Place.create(name: "Big Ed's BBQ", category_id: 4)
Place.create(name: "BR Bar Dining & Dancing", category_id: 4)
Place.create(name: "Bronzeville Wingz", category_id: 4)
Place.create(name: "Brown Sugar Bakery", category_id: 4)
Place.create(name: "Can't Believe It's Not Meat", category_id: 4)
Place.create(name: "Caribana", category_id: 4)
Place.create(name: "Carribbean Jerk Palace", category_id: 4)
Place.create(name: "Chef Sara's Cafe", category_id: 4)
Place.create(name: "Chicago's Home of Chicken & Waffles", category_id: 4)
Place.create(name: "Cleo's On Southern Cuisine", category_id: 4)
Place.create(name: "Crazy Bird Chicken", category_id: 4)
Place.create(name: "Culver's Bronzeville", category_id: 4)
Place.create(name: "Dan's Soul Food and Cafe", category_id: 4)
Place.create(name: "Dat Donut", category_id: 4)
Place.create(name: "Deli King", category_id: 4)

Place.create(name: "Dock's Country Club Hills", category_id: 4)
Place.create(name: "Dock's Bronzeville", category_id: 4)
Place.create(name: "Doughboy's Chicago", category_id: 4)
Place.create(name: "Eleven | Eleven", category_id: 4)
Place.create(name: "Eméche Cakery & Cafe", category_id: 4)
Place.create(name: "Flammin Restaurant & Co.", category_id: 4)
Place.create(name: "Flippin Flavors", category_id: 4)
Place.create(name: "Friistyle Chicago", category_id: 4)
Place.create(name: "Frontier", category_id: 4)
Place.create(name: "FruVé xPress Juicery", category_id: 4)
Place.create(name: "Garifuna Flava", category_id: 4)
Place.create(name: "Garifuna Flava West Loop", category_id: 4)
Place.create(name: "Give Me Some Sugah", category_id: 4)
Place.create(name: "Golden Gloves Cuisine", category_id: 4)
Place.create(name: "Good Life Soul Food Cafe", category_id: 4)
Place.create(name: "Hailey's Hoagies", category_id: 4)
Place.create(name: "Haire's Gulf Shrimp", category_id: 4)
Place.create(name: "Hidden Manna Cafe", category_id: 4)
Place.create(name: "Home of the Hoagy", category_id: 4)
Place.create(name: "Honey 1 BBQ", category_id: 4)
Place.create(name: "Ina Mae Tavern & Packaged Goods", category_id: 4)
Place.create(name: "IntoxiCakes", category_id: 4)
Place.create(name: "Iyanze Bar and Cafe", category_id: 4)
Place.create(name: "Ja' Grill", category_id: 4)
Place.create(name: "Jerk Villa Bar & Grill", category_id: 4)
Place.create(name: "Jamaican Jerk Spice", category_id: 4)
Place.create(name: "Jerk 48", category_id: 4)
Place.create(name: "Jerk Taco Man", category_id: 4)
Place.create(name: "JJ Fish & Chicken", category_id: 4)
Place.create(name: "Josephine's Southern Cooking", category_id: 4)
Place.create(name: "Juiced By Shic", category_id: 4)
Place.create(name: "Just Turkey Restaurant", category_id: 4)
Place.create(name: "Kilwins Hyde Park", category_id: 4)
Place.create(name: "Kizin Creole Restaurant", category_id: 4)
Place.create(name: "Kozy Korner Catering & Deli", category_id: 4)
Place.create(name: "Krazy Hog BBQ", category_id: 4)
Place.create(name: "Lemme Get Ummm", category_id: 4)
Place.create(name: "Lem's Bar-B-Q", category_id: 4)
Place.create(name: "Lexington Betty Smoke House Pullman", category_id: 4)
Place.create(name: "Lexington Betty Smoke House Oak Park", category_id: 4)
Place.create(name: "Litehouse Whole Food Grill", category_id: 4)
Place.create(name: "Live and Believe Nutrition", category_id: 4)
Place.create(name: "Lizzy J Cafe", category_id: 4)
Place.create(name: "Luella's Southern Kitchen", category_id: 4)
Place.create(name: "Mabe's Deli", category_id: 4)
Place.create(name: "MacArthur's Restaurant", category_id: 4)
Place.create(name: "Mae's Que House", category_id: 4)
Place.create(name: "Majani Soulful Vegan Cuisine South Shore", category_id: 4)
Place.create(name: "Majani Soulful Vegan Cuisine Pullman", category_id: 4)
Place.create(name: "Mikkey's Retro Grill", category_id: 4)
Place.create(name: "Mr. Brown's Lounge", category_id: 4)
Place.create(name: "Ms. T's Southern Fried Chicken", category_id: 4)
Place.create(name: "Nita's Gumbo Country Club Hills", category_id: 4)
Place.create(name: "Nita's Gumbo Avalon Park", category_id: 4)
Place.create(name: "Old Fashioned Donuts", category_id: 4)
Place.create(name: "Original Soul Vegetarian", category_id: 4)
Place.create(name: "Pearl's Place Restaurant", category_id: 4)
Place.create(name: "Pink Panini Soups & Salads", category_id: 4)
Place.create(name: "Phlavz Bar & Grille", category_id: 4)
Place.create(name: "Q's Tips & Wings BBQ", category_id: 4)
Place.create(name: "Redwood Luxe Bar and Grill", category_id: 4)
Place.create(name: "R U Hungry?", category_id: 4)
Place.create(name: "Shawn Michelle's Homemade Ice Cream", category_id: 4)
Place.create(name: "Signature Sweets Factory", category_id: 4)
Place.create(name: "Simi's Restaurant", category_id: 4)
Place.create(name: "Sip & Savor Bronzeville", category_id: 4)
Place.create(name: "Sip & Savor Hyde Park", category_id: 4)
Place.create(name: "Sip & Savor Rosenwald", category_id: 4)
Place.create(name: "Sip & Savor South Loop", category_id: 4)
Place.create(name: "6978 Soul Food", category_id: 4)
Place.create(name: "Sizzlin Skillets", category_id: 4)
Place.create(name: "Slice of Bronzeville", category_id: 4)
Place.create(name: "Some Like It Black Creative Arts Bar", category_id: 4)
Place.create(name: "Soulé", category_id: 4)
Place.create(name: "Soul Shack", category_id: 4)
Place.create(name: "South Shore Brew", category_id: 4)
Place.create(name: "Southside African Restaurant", category_id: 4)
Place.create(name: "Surf's Up South Shore", category_id: 4)
Place.create(name: "Sweet Maple Cafe", category_id: 4)
Place.create(name: "Taste 222", category_id: 4)
Place.create(name: "Taylor's Tacos Chicago", category_id: 4)
Place.create(name: "TeaPotBrew Bakery", category_id: 4)
Place.create(name: "The Bureau Bar and Restaurant", category_id: 4)
Place.create(name: "The Full Slab", category_id: 4)
Place.create(name: "The Licking Chicago", category_id: 4)
Place.create(name: "The Slab Bar-B-Que", category_id: 4)
Place.create(name: "The Woodlawn", category_id: 4)
Place.create(name: "The Wrap Bar", category_id: 4)
Place.create(name: "Truth Italian Restaurant", category_id: 4)
Place.create(name: "Turkey Chop", category_id: 4)
Place.create(name: "Two Fish Crab Shack", category_id: 4)
Place.create(name: "Uncle Remus", category_id: 4)
Place.create(name: "Urban Grill Chicago", category_id: 4)
Place.create(name: "Vee-Vee's African Restaurant", category_id: 4)
Place.create(name: "Vegan T'ease", category_id: 4)
Place.create(name: "Virtue Restaurant", category_id: 4)
Place.create(name: "Windy City Ribs & Whiskey", category_id: 4)
Place.create(name: "Kyoto Black Coffee", category_id: 4)
Place.create(name: "The Grail Cafe", category_id: 4)
Place.create(name: "Life's Sweet Inc.", category_id: 4)
Place.create(name: "Juiced By Shic Midlothian", category_id: 4)
Place.create(name: "Juiced By Shic Palos Heights", category_id: 4)
Place.create(name: "B&B's Ice Cream and Candy", category_id: 4)
Place.create(name: "The Common Cup", category_id: 4)
Place.create(name: "Litehouse Whole Food Grill - Evanston", category_id: 4)
Place.create(name: "The Delta", category_id: 4)
Place.create(name: "Vicky's Cafe", category_id: 4)
Place.create(name: "Food on the Run", category_id: 4)
Place.create(name: "Rooh Chicago", category_id: 4)
Place.create(name: "Exquisite Meals", category_id: 4)
Place.create(name: "Powerhouse Restaurant", category_id: 4)
Place.create(name: "Soul and Smoke", category_id: 4)
Place.create(name: "Surf's Up Aurora", category_id: 4)
Place.create(name: "Surf's Up Avondale", category_id: 4)
Place.create(name: "Surf's Up Bronzeville", category_id: 4)
Place.create(name: "Surf's Up Dekalb", category_id: 4)
Place.create(name: "Surf's Up Maywood", category_id: 4)
Place.create(name: "Surf's Up Oak Park", category_id: 4)
Place.create(name: "Surf's Up Romeoville", category_id: 4)
Place.create(name: "Dirty Birds Southern Kitchen", category_id: 4)
Place.create(name: "Hecky's BBQ", category_id: 4)
Place.create(name: "The Long Room", category_id: 4)
Place.create(name: "Mikkey's on Stony", category_id: 4)
Place.create(name: "Grace African Restaurant", category_id: 4)
Place.create(name: "Ethiopian Diamond", category_id: 4)
Place.create(name: "Mogadishu Restaurant", category_id: 4)
Place.create(name: "Denden Eritean Restaurant", category_id: 4)
Place.create(name: "Ras Deshen Ethiopian Restaurant", category_id: 4)
Place.create(name: "Ethiopian Diamond", category_id: 4)
Place.create(name: "Gorée Cuisine", category_id: 4)
Place.create(name: "Demera Ethiopian Restaurant", category_id: 4)
Place.create(name: "Tesfa African Restaurant", category_id: 4)
Place.create(name: "Yassa African Restaurant", category_id: 4)
Place.create(name: "Iya Foods", category_id: 4)
Place.create(name: "Soul Vegan", category_id: 4)
Place.create(name: "That's A Burger", category_id: 4)
Place.create(name: "Lion's Den Eatery", category_id: 4)
Place.create(name: "Miss Lee Good Food", category_id: 4)
Place.create(name: "Ooh Wee Sweet Tea", category_id: 4)
Place.create(name: "Lems BBQ", category_id: 4)
Place.create(name: "Taurus Flavors", category_id: 4)
Place.create(name: "Uncle Joe's Jerk Chicken", category_id: 4)
Place.create(name: "B Gabs Goodies", category_id: 4)
Place.create(name: "Karyn's", category_id: 4)
Place.create(name: "Daisy's", category_id: 4)
Place.create(name: "Baylor Melon Market", category_id: 4)
Place.create(name: "Currency Exchange Cafe", category_id: 4)
Place.create(name: "The Burger Point", category_id: 4)
Place.create(name: "Ms. Biscuit", category_id: 4)
Place.create(name: "Norman's Bistro", category_id: 4)
Place.create(name: "Peach's Restaurant", category_id: 4)
Place.create(name: "Ain't She Sweet Cafe", category_id: 4)
Place.create(name: "Anita's Gumbo", category_id: 4)
Place.create(name: "Pier 31 Restaurant", category_id: 4)
Place.create(name: "Bianca Belle Cuisines", category_id: 4)
Place.create(name: "Berry Berry Sweets", category_id: 4)
Place.create(name: "Ida's Sweet Tooth", category_id: 4)
Place.create(name: "Scatch My Batch", category_id: 4)
Place.create(name: "Penthouse Sweets", category_id: 4)
Place.create(name: "Bella Noir Desserts", category_id: 4)
Place.create(name: "Nadia's Gourmet Grapes", category_id: 4)
Place.create(name: "Laines Bakeshop", category_id: 4)
Place.create(name: "Sweet Blooms Cupcakes", category_id: 4)